package workflow

import (
	"encoding/json"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

type FlagInfo struct {
	Name        string `json:"name"`
	Short       string `json:"short"`
	Type        string `json:"type"`
	Description string `json:"description"`
	Persistent  bool   `json:"persistent"`
}

type FlagGroupInfo struct {
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Example     string     `json:"example"`
	Note        string     `json:"note"`
	Flags       []FlagInfo `json:"flags"`
}

type CommandInfo struct {
	GoFile     string          `json:"go_file"`
	CmdName    string          `json:"cmd_name"` // from godoc comment first word
	VarName    string          `json:"var_name"`
	Doc        string          `json:"doc"`
	Use        string          `json:"use"`
	Short      string          `json:"short"`
	HasCommand bool            `json:"has_command"`
	FlagGroups []FlagGroupInfo `json:"flag_groups"`
	Path       []string        `json:"path"`
}

func parseCommands(dir string) ([]CommandInfo, error) {
	pkgName := filepath.Base(dir)

	// 1. Find root command symbol in the Go source files
	symbolName, isFunc, err := findRootCmdSymbol(dir)
	if err != nil {
		return nil, fmt.Errorf("failed to find root command symbol: %w", err)
	}

	rootExpr := symbolName
	if isFunc {
		rootExpr = symbolName + "()"
	}

	// 2. Write dynamic test file docs_exporter_tmp_test.go
	testPath := filepath.Join(dir, "docs_exporter_tmp_test.go")
	jsonPath := filepath.Join(dir, "docs_metadata_tmp.json")
	defer func() {
		_ = os.Remove(testPath)
		_ = os.Remove(jsonPath)
	}()

	testContent := fmt.Sprintf(strings.ReplaceAll(exporterTestTemplate, "#TAG#", "\x60"), rootExpr)
	if err := os.WriteFile(testPath, []byte(testContent), 0644); err != nil {
		return nil, fmt.Errorf("failed to write dynamic test file: %w", err)
	}

	// 3. Run go test to execute the exporter
	cmd := exec.Command("go", "test", "-run", "^TestExportDocs$", "./"+dir)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return nil, fmt.Errorf("failed to execute dynamic exporter via go test: %w\nOutput:\n%s", err, string(output))
	}

	// 4. Read the generated metadata JSON file
	jsonData, err := os.ReadFile(jsonPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read metadata generated by exporter: %w", err)
	}

	var exportedRoot ExportedCommand
	if err := json.Unmarshal(jsonData, &exportedRoot); err != nil {
		return nil, fmt.Errorf("failed to parse metadata generated by exporter: %w", err)
	}

	fmt.Printf("DEBUG ROOT: %s, SUBCOMMANDS: ", exportedRoot.Name)
	for _, sub := range exportedRoot.Subcommands {
		fmt.Printf("%s, ", sub.Name)
	}
	fmt.Println()

	// 5. Parse source comments from all Go files in dir
	cmdComments, err := parseCommentsFromDir(dir)
	if err != nil {
		return nil, fmt.Errorf("failed to parse comments from source: %w", err)
	}

	if Debug {
		for _, fc := range cmdComments {
			fmt.Printf("DEBUG FILE COMMENT: File: %s, CmdName: %s, NumGroups: %d\n", fc.GoFile, fc.CmdName, len(fc.FlagGroups))
		}
	}

	// 6. Flatten the command tree and merge with comments/flag groups
	flatCmds := flattenCommands(exportedRoot, nil, pkgName, cmdComments)
	
	fmt.Printf("DEBUG FLAT CMDS: ")
	for _, c := range flatCmds {
		fmt.Printf("%s, ", c.CmdName)
	}
	fmt.Println()

	if Debug {
		for _, c := range flatCmds {
			fmt.Printf("DEBUG FLAT CMD: %s (Path: %v, GoFile: %s)\n", c.CmdName, c.Path, c.GoFile)
		}
	}

	return flatCmds, nil
}

type ExportedFlag struct {
	Name        string `json:"name"`
	Short       string `json:"short"`
	Type        string `json:"type"`
	Description string `json:"description"`
	Persistent  bool   `json:"persistent"`
	DefValue    string `json:"def_value"`
}

type ExportedCommand struct {
	Name        string            `json:"name"`
	Use         string            `json:"use"`
	Short       string            `json:"short"`
	Long        string            `json:"long"`
	Flags       []ExportedFlag    `json:"flags"`
	Subcommands []ExportedCommand `json:"subcommands,omitempty"`
}

type parsedFileComments struct {
	GoFile     string
	CmdName    string
	DocBlock   *parsedCommandBlock
	FlagGroups []parsedFlagGroupBlock
}

type parsedCommandBlock struct {
	Name        string
	Description string
	Example     string
	Note        string
}

func findRootCmdSymbol(dir string) (string, bool, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), "_test.go")
	}, parser.ParseComments)
	if err != nil {
		return "", false, err
	}

	isCobraCmdType := func(expr ast.Expr) bool {
		if expr == nil {
			return false
		}
		star, ok := expr.(*ast.StarExpr)
		if !ok {
			return false
		}
		sel, ok := star.X.(*ast.SelectorExpr)
		if !ok {
			return false
		}
		xIdent, ok := sel.X.(*ast.Ident)
		if !ok {
			return false
		}
		return xIdent.Name == "cobra" && sel.Sel.Name == "Command"
	}

	var fallbackVar string
	var fallbackFunc string

	for _, pkg := range pkgs {
		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				switch d := decl.(type) {
				case *ast.GenDecl:
					if d.Tok == token.VAR {
						for _, spec := range d.Specs {
							vspec, ok := spec.(*ast.ValueSpec)
							if !ok {
								continue
							}
							isCmd := false
							if vspec.Type != nil && isCobraCmdType(vspec.Type) {
								isCmd = true
							} else {
								for _, val := range vspec.Values {
									if unary, ok := val.(*ast.UnaryExpr); ok && unary.Op == token.AND {
										if comp, ok := unary.X.(*ast.CompositeLit); ok {
											if sel, ok := comp.Type.(*ast.SelectorExpr); ok {
												if xIdent, ok := sel.X.(*ast.Ident); ok && xIdent.Name == "cobra" && sel.Sel.Name == "Command" {
													isCmd = true
												}
											}
										}
									}
								}
							}
							if isCmd && len(vspec.Names) > 0 {
								name := vspec.Names[0].Name
								if strings.Contains(strings.ToLower(name), "root") {
									return name, false, nil
								}
								fallbackVar = name
							}
						}
					}
				case *ast.FuncDecl:
					isCmd := false
					if d.Type.Results != nil {
						for _, field := range d.Type.Results.List {
							if isCobraCmdType(field.Type) {
								isCmd = true
								break
							}
						}
					}
					if isCmd {
						name := d.Name.Name
						if strings.Contains(strings.ToLower(name), "root") {
							return name, true, nil
						}
						fallbackFunc = name
					}
				}
			}
		}
	}

	if fallbackVar != "" {
		return fallbackVar, false, nil
	}
	if fallbackFunc != "" {
		return fallbackFunc, true, nil
	}

	return "", false, fmt.Errorf("could not find a cobra.Command variable or function in package")
}

func parseCommentsFromDir(dir string) ([]parsedFileComments, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(fi os.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), "_test.go")
	}, parser.ParseComments)
	if err != nil {
		return nil, err
	}

	var results []parsedFileComments

	for _, pkg := range pkgs {
		for fname, file := range pkg.Files {
			var fc parsedFileComments
			fc.GoFile = filepath.Join(dir, filepath.Base(fname))

			for _, cg := range file.Comments {
				text := cg.Text()
				if name, desc, eg, note, ok := parseDocsCommandBlock(text); ok {
					fc.CmdName = name
					fc.DocBlock = &parsedCommandBlock{
						Name:        name,
						Description: desc,
						Example:     eg,
						Note:        note,
					}
				}
				if fgBlock, ok := parseDocsFlagGroupBlock(text); ok {
					fc.FlagGroups = append(fc.FlagGroups, fgBlock)
				}
			}

			if fc.CmdName == "" {
				var foundUse string
				ast.Inspect(file, func(n ast.Node) bool {
					unary, ok := n.(*ast.UnaryExpr)
					if !ok || unary.Op != token.AND {
						return true
					}
					comp, ok := unary.X.(*ast.CompositeLit)
					if !ok {
						return true
					}
					sel, ok := comp.Type.(*ast.SelectorExpr)
					if !ok {
						return true
					}
					xIdent, ok := sel.X.(*ast.Ident)
					if !ok || xIdent.Name != "cobra" || sel.Sel.Name != "Command" {
						return true
					}

					for _, el := range comp.Elts {
						kv, ok := el.(*ast.KeyValueExpr)
						if !ok {
							continue
						}
						keyIdent, ok := kv.Key.(*ast.Ident)
						if !ok {
							continue
						}
						if keyIdent.Name == "Use" {
							foundUse = parseExprString(kv.Value, file)
						}
					}
					return false
				})

				if foundUse != "" {
					words := strings.Fields(foundUse)
					if len(words) > 0 {
						fc.CmdName = words[0]
					}
				}
			}

			if fc.CmdName == "" && filepath.Base(fname) == "root.go" {
				fc.CmdName = "root"
			}

			results = append(results, fc)
		}
	}

	return results, nil
}

func flattenCommands(ec ExportedCommand, parentPath []string, pkgName string, fileComments []parsedFileComments) []CommandInfo {
	var currentPath []string
	if parentPath == nil {
		currentPath = []string{pkgName}
	} else {
		currentPath = append(append([]string{}, parentPath...), ec.Name)
	}

	cmdName := strings.Join(currentPath, "-")

	info := CommandInfo{
		CmdName:    cmdName,
		Use:        ec.Use,
		Short:      ec.Short,
		HasCommand: true,
		Path:       currentPath,
	}

	var matchingComment *parsedFileComments
	for i := range fileComments {
		fc := &fileComments[i]
		if len(parentPath) == 0 {
			if fc.CmdName == "root" || fc.CmdName == pkgName || strings.HasSuffix(fc.GoFile, "root.go") {
				matchingComment = fc
				break
			}
		} else {
			if fc.CmdName == ec.Name {
				matchingComment = fc
				break
			}
		}
	}

	if matchingComment != nil {
		info.GoFile = matchingComment.GoFile
		if matchingComment.DocBlock != nil {
			var docParts []string
			if matchingComment.DocBlock.Description != "" {
				docParts = append(docParts, matchingComment.DocBlock.Description)
			}
			if matchingComment.DocBlock.Example != "" {
				docParts = append(docParts, "### Example\n\n"+matchingComment.DocBlock.Example)
			}
			if matchingComment.DocBlock.Note != "" {
				docParts = append(docParts, ":::note\n"+matchingComment.DocBlock.Note+"\n:::")
			}
			info.Doc = strings.Join(docParts, "\n\n")
		}
	}

	if info.Doc == "" {
		if ec.Long != "" {
			info.Doc = ec.Long
		} else {
			info.Doc = ec.Short
		}
	}

	var allFlags []FlagInfo
	for _, f := range ec.Flags {
		allFlags = append(allFlags, FlagInfo{
			Name:        f.Name,
			Short:       f.Short,
			Type:        f.Type,
			Description: f.Description,
			Persistent:  f.Persistent,
		})
	}

	assigned := make(map[string]bool)
	var flagGroups []FlagGroupInfo

	if matchingComment != nil && len(matchingComment.FlagGroups) > 0 {
		for _, b := range matchingComment.FlagGroups {
			group := FlagGroupInfo{
				Name:        b.Name,
				Description: b.Description,
				Example:     b.Example,
				Note:        b.Note,
			}
			for _, fName := range b.FlagNames {
				if Debug {
					fmt.Printf("DEBUG MATCHING fName: %q for group: %s\n", fName, b.Name)
				}
				for _, f := range allFlags {
					if Debug {
						fmt.Printf("  COMPARING with f.Name: %q\n", f.Name)
					}
					if f.Name == fName {
						group.Flags = append(group.Flags, f)
						assigned[f.Name] = true
						break
					}
				}
			}
			flagGroups = append(flagGroups, group)
		}
	}

	var unassignedFlags []FlagInfo
	for _, f := range allFlags {
		if !assigned[f.Name] {
			unassignedFlags = append(unassignedFlags, f)
		}
	}

	if len(unassignedFlags) > 0 {
		flagGroups = append(flagGroups, FlagGroupInfo{
			Name:  "Flags",
			Flags: unassignedFlags,
		})
	}

	info.FlagGroups = flagGroups

	var subParentPath []string
	if parentPath == nil {
		subParentPath = []string{}
	} else {
		subParentPath = currentPath
	}

	result := []CommandInfo{info}
	for _, sub := range ec.Subcommands {
		result = append(result, flattenCommands(sub, subParentPath, pkgName, fileComments)...)
	}

	return result
}

const exporterTestTemplate = `package main

import (
	"encoding/json"
	"os"
	"testing"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

type ExportedFlag struct {
	Name        string #TAG#json:"name"#TAG#
	Short       string #TAG#json:"short"#TAG#
	Type        string #TAG#json:"type"#TAG#
	Description string #TAG#json:"description"#TAG#
	Persistent  bool   #TAG#json:"persistent"#TAG#
	DefValue    string #TAG#json:"def_value"#TAG#
}

type ExportedCommand struct {
	Name        string            #TAG#json:"name"#TAG#
	Use         string            #TAG#json:"use"#TAG#
	Short       string            #TAG#json:"short"#TAG#
	Long        string            #TAG#json:"long"#TAG#
	Flags       []ExportedFlag    #TAG#json:"flags"#TAG#
	Subcommands []ExportedCommand #TAG#json:"subcommands,omitempty"#TAG#
}

func exportCmd(cmd *cobra.Command) ExportedCommand {
	ec := ExportedCommand{
		Name:  cmd.Name(),
		Use:   cmd.Use,
		Short: cmd.Short,
		Long:  cmd.Long,
	}

	cmd.LocalFlags().VisitAll(func(f *pflag.Flag) {
		ec.Flags = append(ec.Flags, ExportedFlag{
			Name:        f.Name,
			Short:       f.Shorthand,
			Type:        f.Value.Type(),
			Description: f.Usage,
			Persistent:  false,
			DefValue:    f.DefValue,
		})
	})

	cmd.PersistentFlags().VisitAll(func(f *pflag.Flag) {
		for _, lf := range ec.Flags {
			if lf.Name == f.Name {
				return
			}
		}
		ec.Flags = append(ec.Flags, ExportedFlag{
			Name:        f.Name,
			Short:       f.Shorthand,
			Type:        f.Value.Type(),
			Description: f.Usage,
			Persistent:  true,
			DefValue:    f.DefValue,
		})
	})

	for _, sub := range cmd.Commands() {
		if sub.Name() == "help" {
			continue
		}
		ec.Subcommands = append(ec.Subcommands, exportCmd(sub))
	}

	return ec
}

func TestExportDocs(t *testing.T) {
	root := %s
	ec := exportCmd(root)
	data, err := json.Marshal(ec)
	if err != nil {
		t.Fatal(err)
	}
	err = os.WriteFile("docs_metadata_tmp.json", data, 0644)
	if err != nil {
		t.Fatal(err)
	}
}
`

func parseExprString(expr ast.Expr, file *ast.File) string {
	switch e := expr.(type) {
	case *ast.BasicLit:
		if e.Kind == token.STRING {
			return strings.Trim(e.Value, "`\"")
		}
	case *ast.Ident:
		if file != nil {
			if val := lookupIdentValue(e.Name, file); val != "" {
				return val
			}
		}
		return e.Name
	case *ast.BinaryExpr:
		if e.Op == token.ADD {
			return parseExprString(e.X, file) + parseExprString(e.Y, file)
		}
	}
	return ""
}

func lookupIdentValue(name string, file *ast.File) string {
	if file == nil {
		return ""
	}
	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || (genDecl.Tok != token.CONST && genDecl.Tok != token.VAR) {
			continue
		}
		for _, spec := range genDecl.Specs {
			vspec, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			for i, ident := range vspec.Names {
				if ident.Name == name {
					if i < len(vspec.Values) {
						return parseExprString(vspec.Values[i], nil)
					}
				}
			}
		}
	}
	return ""
}

func parseCommentGroup(text string) (groupName, desc, example string, isGroup bool) {
	lines := strings.Split(text, "\n")
	var parsingDesc, parsingExample bool
	var descLines, exampleLines []string

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "@group:") {
			groupName = strings.TrimSpace(strings.TrimPrefix(trimmed, "@group:"))
			isGroup = true
			parsingDesc = false
			parsingExample = false
			continue
		}
		if strings.HasPrefix(trimmed, "@description:") {
			parsingDesc = true
			parsingExample = false
			rest := strings.TrimSpace(strings.TrimPrefix(trimmed, "@description:"))
			if rest != "" {
				descLines = append(descLines, rest)
			}
			continue
		}
		if strings.HasPrefix(trimmed, "@example:") {
			parsingExample = true
			parsingDesc = false
			rest := strings.TrimSpace(strings.TrimPrefix(trimmed, "@example:"))
			if rest != "" {
				exampleLines = append(exampleLines, rest)
			}
			continue
		}

		if parsingDesc {
			descLines = append(descLines, line)
		} else if parsingExample {
			exampleLines = append(exampleLines, line)
		}
	}

	if isGroup {
		desc = cleanBlockText(descLines)
		example = cleanBlockText(exampleLines)
	}
	return
}

func cleanBlockText(lines []string) string {
	if len(lines) == 0 {
		return ""
	}
	minChars := -1
	for _, l := range lines {
		if strings.TrimSpace(l) == "" {
			continue
		}
		chars := 0
		for _, r := range l {
			if r == ' ' || r == '\t' {
				chars++
			} else {
				break
			}
		}
		if minChars == -1 || chars < minChars {
			minChars = chars
		}
	}
	if minChars == -1 {
		minChars = 0
	}

	var cleaned []string
	for _, l := range lines {
		if len(l) <= minChars {
			cleaned = append(cleaned, "")
		} else {
			cleaned = append(cleaned, strings.TrimRight(l[minChars:], " \t"))
		}
	}
	start := 0
	for start < len(cleaned) && cleaned[start] == "" {
		start++
	}
	end := len(cleaned)
	for end > start && cleaned[end-1] == "" {
		end--
	}
	return strings.Join(cleaned[start:end], "\n")
}

func parseGoFile(filePath string) (CommandInfo, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filePath, nil, parser.ParseComments)
	if err != nil {
		return CommandInfo{}, err
	}

	info := CommandInfo{
		GoFile: filePath,
	}

	// Helper to check if a type is *cobra.Command
	isCobraCmdType := func(expr ast.Expr) bool {
		star, ok := expr.(*ast.StarExpr)
		if !ok {
			return false
		}
		sel, ok := star.X.(*ast.SelectorExpr)
		if !ok {
			return false
		}
		xIdent, ok := sel.X.(*ast.Ident)
		if !ok {
			return false
		}
		return xIdent.Name == "cobra" && sel.Sel.Name == "Command"
	}

	// Helper to extract flag info from a CallExpr
	extractFlagInfo := func(call *ast.CallExpr) (name, short, flagType, description string, persistent, ok bool) {
		sel, okSel := call.Fun.(*ast.SelectorExpr)
		if !okSel {
			return "", "", "", "", false, false
		}
		funName := sel.Sel.Name
		recvCall, okRecvCall := sel.X.(*ast.CallExpr)
		if !okRecvCall {
			return "", "", "", "", false, false
		}
		recvSel, okRecvSel := recvCall.Fun.(*ast.SelectorExpr)
		if !okRecvSel || (recvSel.Sel.Name != "Flags" && recvSel.Sel.Name != "PersistentFlags") {
			return "", "", "", "", false, false
		}
		persistent = recvSel.Sel.Name == "PersistentFlags"

		isFlagMethod := false
		for _, prefix := range []string{"Bool", "String", "Int", "Duration", "Float", "Var"} {
			if strings.HasPrefix(funName, prefix) {
				isFlagMethod = true
				break
			}
		}
		if !isFlagMethod {
			return "", "", "", "", false, false
		}

		args := call.Args
		if strings.HasSuffix(funName, "VarP") {
			if len(args) >= 5 {
				name = parseExprString(args[1], file)
				short = parseExprString(args[2], file)
				description = parseExprString(args[4], file)
				flagType = strings.TrimSuffix(funName, "VarP")
				ok = true
			}
		} else if strings.HasSuffix(funName, "Var") {
			if len(args) >= 4 {
				name = parseExprString(args[1], file)
				short = ""
				description = parseExprString(args[3], file)
				flagType = strings.TrimSuffix(funName, "Var")
				ok = true
			}
		} else {
			if strings.HasSuffix(funName, "P") {
				if len(args) >= 4 {
					name = parseExprString(args[0], file)
					short = parseExprString(args[1], file)
					description = parseExprString(args[3], file)
					flagType = strings.TrimSuffix(funName, "P")
					ok = true
				}
			} else {
				if len(args) >= 3 {
					name = parseExprString(args[0], file)
					short = ""
					description = parseExprString(args[2], file)
					flagType = funName
					ok = true
				}
			}
		}
		return
	}

	// Helper to find &cobra.Command inside a node (e.g. FuncDecl or ValueSpec)
	findCobraCommandInNode := func(node ast.Node) (use, short string, found bool) {
		ast.Inspect(node, func(n ast.Node) bool {
			unary, ok := n.(*ast.UnaryExpr)
			if !ok || unary.Op != token.AND {
				return true
			}
			comp, ok := unary.X.(*ast.CompositeLit)
			if !ok {
				return true
			}
			sel, ok := comp.Type.(*ast.SelectorExpr)
			if !ok {
				return true
			}
			xIdent, ok := sel.X.(*ast.Ident)
			if !ok || xIdent.Name != "cobra" || sel.Sel.Name != "Command" {
				return true
			}

			found = true
			for _, el := range comp.Elts {
				kv, ok := el.(*ast.KeyValueExpr)
				if !ok {
					continue
				}
				keyIdent, ok := kv.Key.(*ast.Ident)
				if !ok {
					continue
				}
				if keyIdent.Name == "Use" {
					use = parseExprString(kv.Value, file)
				} else if keyIdent.Name == "Short" {
					short = parseExprString(kv.Value, file)
				}
			}
			return false
		})
		return
	}

	// Inspect top-level declarations to find command definition and set basic info
	for _, decl := range file.Decls {
		switch d := decl.(type) {
		case *ast.GenDecl:
			if d.Tok == token.VAR {
				for _, spec := range d.Specs {
					vspec, ok := spec.(*ast.ValueSpec)
					if !ok {
						continue
					}
					isCmd := false
					if vspec.Type != nil && isCobraCmdType(vspec.Type) {
						isCmd = true
					}
					var use, short string
					for _, val := range vspec.Values {
						if u, s, ok := findCobraCommandInNode(val); ok {
							isCmd = true
							if use == "" {
								use = u
							}
							if short == "" {
								short = s
							}
						}
					}
					if isCmd {
						info.HasCommand = true
						if len(vspec.Names) > 0 {
							info.VarName = vspec.Names[0].Name
						}
						info.Use = use
						info.Short = short
						var commentGroup *ast.CommentGroup
						if vspec.Doc != nil {
							commentGroup = vspec.Doc
						} else if d.Doc != nil {
							commentGroup = d.Doc
						}
						setDocAndName(&info, commentGroup)
						break
					}
				}
			}
		case *ast.FuncDecl:
			isCmd := false
			if d.Type.Results != nil {
				for _, field := range d.Type.Results.List {
					if isCobraCmdType(field.Type) {
						isCmd = true
						break
					}
				}
			}

			if isCmd {
				info.HasCommand = true
				info.VarName = d.Name.Name
				if u, s, ok := findCobraCommandInNode(d.Body); ok {
					info.Use = u
					info.Short = s
				}
				setDocAndName(&info, d.Doc)
				break
			}
		}
		if info.HasCommand {
			break
		}
	}

	if info.HasCommand {
		type ASTNodeWithLine struct {
			Line     int
			Comment  *ast.CommentGroup
			FlagCall *ast.CallExpr
		}
		var items []ASTNodeWithLine

		for _, cg := range file.Comments {
			items = append(items, ASTNodeWithLine{
				Line:    fset.Position(cg.Pos()).Line,
				Comment: cg,
			})
		}

		ast.Inspect(file, func(n ast.Node) bool {
			if call, ok := n.(*ast.CallExpr); ok {
				if _, _, _, _, _, isFlag := extractFlagInfo(call); isFlag {
					items = append(items, ASTNodeWithLine{
						Line:     fset.Position(call.Pos()).Line,
						FlagCall: call,
					})
				}
			}
			return true
		})

		sort.Slice(items, func(i, j int) bool {
			return items[i].Line < items[j].Line
		})

		// Check if we have any @docs-flag-group block in the file comments
		hasDocsFlagGroup := false
		for _, item := range items {
			if item.Comment != nil {
				txt := item.Comment.Text()
				if strings.Contains(txt, "@docs-flag-group:") || strings.Contains(txt, "@docs-flag-group") {
					hasDocsFlagGroup = true
					break
				}
			}
		}

		if hasDocsFlagGroup {
			// New System: organize flags based on @docs-flag-group blocks
			var parsedBlocks []parsedFlagGroupBlock
			for _, item := range items {
				if item.Comment != nil {
					block, parsed := parseDocsFlagGroupBlock(item.Comment.Text())
					if parsed {
						parsedBlocks = append(parsedBlocks, block)
					}
				}
			}

			// Gather all flags parsed from the AST
			var allFlags []FlagInfo
			for _, item := range items {
				if item.FlagCall != nil {
					name, short, flagType, desc, persistent, ok := extractFlagInfo(item.FlagCall)
					if ok {
						allFlags = append(allFlags, FlagInfo{
							Name:        name,
							Short:       short,
							Type:        flagType,
							Description: desc,
							Persistent:  persistent,
						})
					}
				}
			}

			// Track assigned flags
			assigned := make(map[string]bool)
			var flagGroups []FlagGroupInfo

			for _, b := range parsedBlocks {
				group := FlagGroupInfo{
					Name:        b.Name,
					Description: b.Description,
					Example:     b.Example,
					Note:        b.Note,
				}
				for _, fName := range b.FlagNames {
					// Find the flag in parsed flags
					for _, f := range allFlags {
						if f.Name == fName {
							group.Flags = append(group.Flags, f)
							assigned[f.Name] = true
							break
						}
					}
				}
				flagGroups = append(flagGroups, group)
			}

			// Add unassigned flags to default group
			var unassignedFlags []FlagInfo
			for _, f := range allFlags {
				if !assigned[f.Name] {
					unassignedFlags = append(unassignedFlags, f)
				}
			}

			if len(unassignedFlags) > 0 {
				flagGroups = append(flagGroups, FlagGroupInfo{
					Name:  "Flags",
					Flags: unassignedFlags,
				})
			}

			info.FlagGroups = flagGroups

		} else {
			// Old System: fallback to @group: comments and encounter order
			var flagGroups []FlagGroupInfo
			var currentGroup *FlagGroupInfo

			for _, item := range items {
				if item.Comment != nil {
					gName, desc, example, isGroup := parseCommentGroup(item.Comment.Text())
					if isGroup {
						if currentGroup != nil {
							flagGroups = append(flagGroups, *currentGroup)
						}
						currentGroup = &FlagGroupInfo{
							Name:        gName,
							Description: desc,
							Example:     example,
						}
					}
				} else if item.FlagCall != nil {
					name, short, flagType, desc, persistent, ok := extractFlagInfo(item.FlagCall)
					if ok {
						if currentGroup == nil {
							currentGroup = &FlagGroupInfo{
								Name: "Flags",
							}
						}
						currentGroup.Flags = append(currentGroup.Flags, FlagInfo{
							Name:        name,
							Short:       short,
							Type:        flagType,
							Description: desc,
							Persistent:  persistent,
						})
					}
				}
			}
			if currentGroup != nil {
				flagGroups = append(flagGroups, *currentGroup)
			}

			info.FlagGroups = flagGroups
		}
	}

	return info, nil
}

func setDocAndName(info *CommandInfo, commentGroup *ast.CommentGroup) {
	if commentGroup == nil {
		return
	}
	docText := commentGroup.Text()
	name, description, example, note, parsed := parseDocsCommandBlock(docText)
	if parsed {
		if name != "" {
			info.CmdName = name
		}
		var docParts []string
		if description != "" {
			docParts = append(docParts, description)
		}
		if example != "" {
			docParts = append(docParts, "### Example\n\n"+example)
		}
		if note != "" {
			docParts = append(docParts, ":::note\n"+note+"\n:::")
		}
		info.Doc = strings.Join(docParts, "\n\n")
	} else {
		info.Doc = strings.TrimSpace(docText)
		lines := strings.Split(info.Doc, "\n")
		if len(lines) > 0 && len(lines[0]) > 0 {
			words := strings.Fields(lines[0])
			if len(words) > 0 {
				info.CmdName = strings.Trim(words[0], "`\"'")
			}
		}
	}
}

type parsedFlagGroupBlock struct {
	Name        string
	Description string
	Example     string
	Note        string
	FlagNames   []string
}

func parseDocsFlagGroupBlock(text string) (block parsedFlagGroupBlock, parsed bool) {
	lines := strings.Split(text, "\n")
	startIndex := -1
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "@docs-flag-group:") || strings.HasPrefix(trimmed, "@docs-flag-group") {
			startIndex = i
			break
		}
	}
	if startIndex == -1 {
		return
	}
	parsed = true

	var currentKey string
	var currentValLines []string

	flush := func() {
		if currentKey == "" {
			return
		}
		val := cleanBlockText(currentValLines)
		switch currentKey {
		case "name":
			block.Name = val
		case "description":
			block.Description = val
		case "example":
			block.Example = val
		case "note":
			block.Note = val
		case "flags":
			for _, part := range strings.Split(val, ",") {
				trimmedPart := strings.TrimSpace(part)
				if trimmedPart != "" {
					block.FlagNames = append(block.FlagNames, trimmedPart)
				}
			}
		}
		currentKey = ""
		currentValLines = nil
	}

	for _, line := range lines[startIndex+1:] {
		trimmed := strings.TrimSpace(line)
		var nextKey string
		for _, k := range []string{"name:", "description:", "example:", "note:", "flags:"} {
			if strings.HasPrefix(trimmed, k) {
				nextKey = strings.TrimSuffix(k, ":")
				break
			}
		}

		if nextKey != "" {
			flush()
			currentKey = nextKey
			rest := strings.TrimSpace(strings.TrimPrefix(trimmed, currentKey+":"))
			if rest != "" {
				currentValLines = append(currentValLines, rest)
			}
		} else {
			if currentKey != "" {
				currentValLines = append(currentValLines, line)
			}
		}
	}
	flush()
	return
}

func parseDocsCommandBlock(text string) (name, description, example, note string, parsed bool) {
	lines := strings.Split(text, "\n")
	startIndex := -1
	for i, line := range lines {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "@docs-command:") || strings.HasPrefix(trimmed, "@docs-command") {
			startIndex = i
			break
		}
	}
	if startIndex == -1 {
		return
	}
	parsed = true

	var currentKey string
	var currentValLines []string

	flush := func() {
		if currentKey == "" {
			return
		}
		val := cleanBlockText(currentValLines)
		switch currentKey {
		case "name":
			name = val
		case "description":
			description = val
		case "example":
			example = val
		case "note":
			note = val
		}
		currentKey = ""
		currentValLines = nil
	}

	for _, line := range lines[startIndex+1:] {
		trimmed := strings.TrimSpace(line)
		// Check if this line starts a new key
		var nextKey string
		for _, k := range []string{"name:", "description:", "example:", "note:"} {
			if strings.HasPrefix(trimmed, k) {
				nextKey = strings.TrimSuffix(k, ":")
				break
			}
		}

		if nextKey != "" {
			flush()
			currentKey = nextKey
			rest := strings.TrimSpace(strings.TrimPrefix(trimmed, currentKey+":"))
			if rest != "" {
				currentValLines = append(currentValLines, rest)
			}
		} else {
			if currentKey != "" {
				currentValLines = append(currentValLines, line)
			}
		}
	}
	flush()
	return
}

func parseCommandRelations(dir string) (map[string]string, error) {
	files, err := os.ReadDir(dir)
	if err != nil {
		return nil, err
	}

	relations := make(map[string]string)
	fset := token.NewFileSet()

	for _, f := range files {
		if f.IsDir() {
			continue
		}
		name := f.Name()
		if !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") || name == "main.go" {
			continue
		}

		filePath := filepath.Join(dir, name)
		file, err := parser.ParseFile(fset, filePath, nil, parser.ParseComments)
		if err != nil {
			continue
		}

		// Inspect all declarations in this file
		for _, decl := range file.Decls {
			if fdecl, ok := decl.(*ast.FuncDecl); ok {
				funcName := fdecl.Name.Name
				if fdecl.Body == nil {
					continue
				}
				ast.Inspect(fdecl.Body, func(n ast.Node) bool {
					call, ok := n.(*ast.CallExpr)
					if !ok {
						return true
					}
					sel, ok := call.Fun.(*ast.SelectorExpr)
					if !ok || sel.Sel.Name != "AddCommand" {
						return true
					}

					var parentName string
					if ident, ok := sel.X.(*ast.Ident); ok {
						if funcName == "init" || (ident.Name != "cmd" && ident.Name != "c") {
							parentName = ident.Name
						} else {
							parentName = funcName
						}
					} else {
						parentName = funcName
					}

					for _, arg := range call.Args {
						childName := resolveCommandRefName(arg)
						if childName != "" {
							relations[childName] = parentName
						}
					}
					return true
				})
			}
		}
	}
	return relations, nil
}

func resolveCommandRefName(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.CallExpr:
		if ident, ok := e.Fun.(*ast.Ident); ok {
			return ident.Name
		}
		if sel, ok := e.Fun.(*ast.SelectorExpr); ok {
			return sel.Sel.Name
		}
	case *ast.Ident:
		return e.Name
	case *ast.SelectorExpr:
		return e.Sel.Name
	}
	return ""
}
